export const GET_IMAGES = 'GET_IMAGES';
export const IMAGES_LOADED = 'IMAGES_LOADED'
export const IMAGES_FAILED = 'IMAGES_FAILED'

export const UPDATE_FAVORITE_SUCCESS = 'UPDATE_FAVORITE_SUCCESS'
export const UPDATE_FAVORITE_FAILED = 'UPDATE_FAVORITE_FAILED'